In [1]:
from tdc.single_pred import Tox
data = Tox(name = 'Skin Reaction')
split = data.get_split(method='scaffold')

Found local copy...
Loading...
Done!
100%|██████████| 404/404 [00:00<00:00, 6594.28it/s]

In [2]:
print(data)

<tdc.single_pred.tox.Tox object at 0x1057831c0>

In [3]:
print(split.keys())

dict_keys(['train', 'valid', 'test'])

In [4]:
split["train"].columns

Index(['Drug_ID', 'Drug', 'Y'], dtype='object')

In [5]:
split["train"].head()

,Drug_ID,Drug,Y
0,"[4-(Ethoxymethyl)-2,6-dimethoxyphenyl]boronic ...",CCOCc1cc(OC)c(B(O)O)c(OC)c1,0
1,"1-(3',4',5'-Tetramethoxy-phenyl)-4,4-dimethylp...",COc1cc(C(=O)CC(=O)C(C)(C)C)cc(OC)c1OC,0
2,"1-[3,5-Bis(trifluoromethyl)phenyl]-N-methyleth...",CNC(C)c1cc(C(F)(F)F)cc(C(F)(F)F)c1,0
3,1-Phenylpropylamine,CCC(N)c1ccccc1,0
4,2-[(Benzyloxy)-imino]malonic acid,O=C(O)C(=NOCc1ccccc1)C(=O)O,0

In [6]:
split["train"].shape, split["valid"].shape, split["test"].shape

((282, 3), (40, 3), (82, 3))

In [7]:
print(split["train"]["Y"].value_counts())

Y
1    205
0     77
Name: count, dtype: int64

In [8]:
for k in split:
    print(f"{k}:")
    print(split[k]["Y"].value_counts())
    print(f"total: {len(split[k])}")
    print()

train:
Y
1    205
0     77
Name: count, dtype: int64
total: 282

valid:
Y
1    22
0    18
Name: count, dtype: int64
total: 40

test:
Y
1    47
0    35
Name: count, dtype: int64
total: 82

In [9]:
df = data.get_data()

In [10]:
df

,Drug_ID,Drug,Y
0,(16-b)-21-(Acetyloxy)-17-hydroxy-16-methylpreg...,CC(=O)OCC(=O)C1(O)C(C)CC2C3CCC4=CC(=O)C=CC4(C)...,0
1,(2-Bromo-5-propoxyphenyl)-(2-hydroxy-4-methoxy...,CCCOc1ccc(Br)c(C(=O)c2ccc(OC)cc2O)c1,0
2,(2E)-2-Methyl-2-butenal,CC=C(C)C=O,0
3,(2-oxo-1-phenylpyrrolidin-3-yl)-Triphenylphosp...,O=C1C([PH](c2ccccc2)(c2ccccc2)c2ccccc2)CCN1c1c...,0
4,(4Z)-2-Methyl-6-methylene-4-octene,C=C(C=CCC(C)C)CC,0
...,...,...,...
399,Maleic anhydride,O=C1C=CC(=O)O1,1
400,"N,N-dimethyl-4-nitrosoaniline",CN(C)c1ccc(N=O)cc1,1
401,Phthalic anhydride,O=C1OC(=O)c2ccccc21,1
402,Propyl gallate,CCCOC(=O)c1cc(O)c(O)c(O)c1,1
403,Squaric acid,O=c1c(O)c(O)c1=O,1

In [11]:
len(df)

404